"""empty message

Revision ID: 3718af360189
Revises: 5b0c3c4cfe5d
Create Date: 2022-12-21 21:26:00.104918

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3718af360189'
down_revision = '5b0c3c4cfe5d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('car', schema=None) as batch_op:
        batch_op.drop_column('sale_price')
        batch_op.drop_column('mpg')
        batch_op.drop_column('new_used')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('car', schema=None) as batch_op:
        batch_op.add_column(sa.Column('new_used', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('mpg', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('sale_price', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
