"""empty message

Revision ID: 5b0c3c4cfe5d
Revises: e0599b8dbd25
Create Date: 2022-12-21 21:21:57.713033

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b0c3c4cfe5d'
down_revision = 'e0599b8dbd25'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('car',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('make', sa.String(length=150), nullable=True),
    sa.Column('model', sa.String(length=200), nullable=True),
    sa.Column('sale_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('color', sa.String(length=150), nullable=True),
    sa.Column('year', sa.Numeric(precision=4), nullable=True),
    sa.Column('mpg', sa.String(length=100), nullable=True),
    sa.Column('new_used', sa.String(length=20), nullable=True),
    sa.Column('user_token', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['user_token'], ['user.token'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('car')
    # ### end Alembic commands ###
